# Generated by Django 5.2 on 2025-05-03 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('imagen_representativa', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_imagen', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_importacion', models.DateField(blank=True, null=True)),
                ('ficha_tecnica', models.TextField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoria')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.CharField(max_length=255)),
                ('es_imagen_principal', models.BooleanField(default=False)),
                ('fecha_added', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'db_table': 'imagenes_producto',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id_resena', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_resena', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_usuario', models.CharField(blank=True, max_length=15, null=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='productos.usuario')),
            ],
            options={
                'db_table': 'resenas',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('estrellas', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='productos.usuario')),
            ],
            options={
                'db_table': 'calificaciones',
            },
        ),
        migrations.CreateModel(
            name='VideoProducto',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False)),
                ('url_video', models.CharField(max_length=255)),
                ('titulo_video', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_video', models.TextField(blank=True, null=True)),
                ('es_video_principal', models.BooleanField(default=False)),
                ('fecha_added', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'db_table': 'videos_producto',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id_like', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_like', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='productos.usuario')),
            ],
            options={
                'db_table': 'likes',
                'unique_together': {('id_producto', 'id_usuario')},
            },
        ),
    ]
